services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: apply_digital_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d apply_digital_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api-service
    container_name: api-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apply_digital_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    restart: on-failure

  scheduler-service:
    build:
      context: .
      dockerfile: Dockerfile.scheduler-service
    container_name: scheduler-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apply_digital_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      ALGOLIA_JAVA-ARTICLES_URL: https://hn.algolia.com/api/v1/search_by_date?query=java
      SCHEDULER_FETCH_RATE: 60000

volumes:
  postgres_data:
