spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apply_digital_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

algolia:
  java-articles:
    url: https://hn.algolia.com/api/v1/search_by_date?query=java

server:
  port: 9090